CREATE TABLE Mesas(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    NumeroMesa INT NOT NULL,
    QuantidadeClientes INT NOT NULL,
    status ENUM('livre', 'ocupada') DEFAULT 'livre'
);

CREATE TABLE Comandas(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    MesaId INT NOT NULL,
    NomeCliente VARCHAR(100) NOT NULL,

    FOREIGN KEY (MesaId) REFERENCES Mesas(Id) ON DELETE CASCADE
);

CREATE TABLE ItensComanda(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    ComandaId INT NOT NULL,
    Item VARCHAR(100) NOT NULL,
    Quantidade INT NOT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    
    FOREIGN KEY (ComandaId) REFERENCES Comandas(Id) ON DELETE CASCADE
);

CREATE TABLE Produtos (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    Categoria VARCHAR(50)
);